{% set name = "django-bakery" %}
{% set version = "0.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-bakery-{{ version }}.tar.gz
  sha256: 10e32f7fd312f5a98e927fb73b5fbcef749892be88a80434d4b7aa985e0b7507

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - django >=4.2
    - six >1.5.2
    - boto3 >=1.4.4
    - fs >=2.0.17

test:
  imports:
    - bakery
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://www.github.com/palewire/django-bakery/
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'A set of helpers for baking your Django site out as flat files'
  description: |
    A set of helpers for baking your Django site out as flat files
  doc_url: https://django-bakery.readthedocs.io/en/latest/
  dev_url: https://github.com/datadesk/django-bakery

extra:
  recipe-maintainers:
    - cshaley
    - rxm7706
    - sannykr
