travis:
  secure:
    BINSTAR_TOKEN: k2V44jZE9aUWyy44/YTNT0W/BDuxslSVY+ue7rUm4xjJtBgUU3av9ldm3myaXble1qbks+tb9561nafZ0C6GsPepgbfYWZx5VCp2kZ59emRLOkhSv2zb51Br9JNeLQCDCA9AIA0GiY8JfPu78I5E+y1y0I6AN3xAF0Nq/PMlZmC8U22PnjncoeM/sB7G1bGazy60awxYl4MscvubMyVa/nZMRdzf96PFDoWwDEi4Xm5AZc8qOtKZ/VgzPzJxkndxrLJ7hT0q6EORGhrC35+7EqTqGSDQnj9NwCozSNuYSnhO83VpnpVc8s+FpezHdJRbCyto4yukM66piORLc4lA9fexvM1249iDv4XFCSuNUoq1qUXzJGRc6XXkwRsHsA+fHXi6dKY4QmkvY4oRev+8qdWNJIDg4RK0g7n4cwF4f9J3sXKI9ceIiAc1y37c0KBBWiAmwMCTFGA9Z12a8a6SvSh9fpc5Gn4l2M3TIuH+GnsFfvS32/Ys6iydgAlpKFsWC+9SU+LdfdEwKhJ+eKqkD9GoSv+VOMLm9NphOfEQiCMHh59H+mUYkrHDbNyfmGucWadhqodCfzoN4Et1h/NE5TGeGTqpkFQURByviv7HhVfvI98rNJI5N00GejhvzHOUy1Rduiqb05S56QXe4P+M1+l+rkDKgHAGn985BE7Hm7E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
