travis:
  secure:
    BINSTAR_TOKEN: Nw+xqYahS7kv1FeXqHX8cBH39XDGXnppVMeKfKaZvdF05lAcUxOVOlZECu0eNE7Ol+MgMNa3b6WGIDfyCww9ONRYa7s76wb+IPFRKW4wKlkeOKwIOEI98lliJC6bTvjgMlB8jVA6fnP9ew6XFmOacKN6UtVViIShI37UHSSGQg/HYyLe7GfznZDMRAvLalJAQEyEkCcyofaqDaHoM/v0fu7YlTeA2IiSscr2+scG9SqSQJDxm6tJotxxoEhEXQpD0TU83tXMc+yaJS4SzBFKgsxU5ApaqXFHDNaIcPtnemSioQsxcdtPbvKK8evY9lMHFuGcS+O2u8olnRs4zMYeNF1CEklGQ1fy65LXEFCd78Wa5N61kVwrhC0xzoxA5dXdYEdqpfPdpOjI6LE/dr7dKdzsE2BkkfjeUUvVgNVKBdiAY/5Nm7QqJIZElo9tH9xo5Ve0c0GZqdqzl/hlxTV23DSrX/7SH/Oh4b0/Pd+cdi4Qr0f6QjLzAEoo+7YUne8q5KtpW+giJ99v5/+gmzQ3zlqh3f4jel8fYUJWk51KnNdlZDrLkSDv1TlkJDnLdO9EjAIxV1m+y7wnrKKIQv07vfBHAYbtf4/COpCOUrvBCZigZ8rVyQLzjNwYa0JYrw50zDvh+N/VGZgw0CJiWR6opfWcqN8CyC91S1eWSA2rUfY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
